# Generated by Django 3.0.8 on 2020-08-21 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_post_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_name',
        ),
    ]
