# Generated by Django 3.0.8 on 2020-08-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200822_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_commented',
        ),
    ]
